import type { Aircraft, User, FlightSubject, LaunchMethod, Flight, PersonalLogEntry, AircraftLogEntry, Organization } from './types'

export const mockOrganization: Organization = {
  id: 'org-1',
  name: '大学航空部',
  invite_code: 'GLIDER01',
  default_departure_airports: ['大利根飛行場', '妻沼滑空場', '板倉滑空場'],
  default_arrival_airports: ['大利根飛行場', '妻沼滑空場', '板倉滑空場'],
}

export const mockUsers: User[] = [
  { id: 'u1', name: '山田 太郎', email: 'yamada@example.com', role: 'operator', organization_id: 'org-1', is_active: true, created_at: '2024-04-01T00:00:00Z' },
  { id: 'u2', name: '鈴木 花子', email: 'suzuki@example.com', role: 'member', organization_id: 'org-1', is_active: true, created_at: '2024-04-01T00:00:00Z' },
  { id: 'u3', name: '田中 一郎', email: 'tanaka@example.com', role: 'instructor', organization_id: 'org-1', is_active: true, created_at: '2024-04-01T00:00:00Z' },
  { id: 'u4', name: '佐藤 次郎', email: 'sato@example.com', role: 'admin', organization_id: 'org-1', is_active: true, created_at: '2024-04-01T00:00:00Z' },
]

export const mockAircraft: Aircraft[] = [
  {
    id: 'a1',
    display_order: 1,
    registration_number: 'JA21MA',
    aircraft_type: 'ASK-21',
    aircraft_category: 'glider',
    aircraft_status: 'active',
    is_visible: true,
    aircraft_initial_airframe_time: 12000,
    aircraft_initial_flight_count: 850,
    aircraft_initial_takeoff_count: 850,
    aircraft_initial_landing_count: 850,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'a2',
    display_order: 2,
    registration_number: 'JA02W',
    aircraft_type: 'ASW-19',
    aircraft_category: 'glider',
    aircraft_status: 'active',
    is_visible: true,
    aircraft_memo: '2026/06 耐空検査完了',
    aircraft_initial_airframe_time: 8400,
    aircraft_initial_flight_count: 620,
    aircraft_initial_takeoff_count: 620,
    aircraft_initial_landing_count: 620,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-06-28T00:00:00Z',
  },
  {
    id: 'a3',
    display_order: 3,
    registration_number: 'JA342K',
    aircraft_type: 'Duo Discus',
    aircraft_category: 'glider',
    aircraft_status: 'maintenance',
    is_visible: true,
    aircraft_memo: '主翼点検のため整備中（〜7月中旬予定）',
    aircraft_initial_airframe_time: 15600,
    aircraft_initial_flight_count: 1020,
    aircraft_initial_takeoff_count: 1020,
    aircraft_initial_landing_count: 1020,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-07-01T00:00:00Z',
  },
  {
    id: 'a4',
    registration_number: 'JA4123',
    aircraft_type: 'C172',
    aircraft_category: 'airplane',
    aircraft_status: 'active',
    is_visible: true,
    aircraft_initial_airframe_time: 54000,
    aircraft_initial_flight_count: 3200,
    aircraft_initial_takeoff_count: 3200,
    aircraft_initial_landing_count: 3200,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
]

export const mockSubjects: FlightSubject[] = [
  { id: 's1', name: '基本操縦', display_order: 1, is_active: true },
  { id: 's2', name: '索道飛行', display_order: 2, is_active: true },
  { id: 's3', name: '野外飛行', display_order: 3, is_active: true },
  { id: 's4', name: '場周経路', display_order: 4, is_active: true },
  { id: 's5', name: '単独飛行', display_order: 5, is_active: true },
  { id: 's6', name: '技量審査', display_order: 6, is_active: true },
]

export const mockLaunchMethods: LaunchMethod[] = [
  { id: 'lm1', name: 'ウィンチ曳航', display_order: 1, is_active: true },
  { id: 'lm2', name: '航空機曳航', display_order: 2, is_active: true },
  { id: 'lm3', name: '自力発航', display_order: 3, is_active: true },
]

const today = new Date().toISOString().split('T')[0]

export const mockFlights: Flight[] = [
  {
    id: 'f1',
    aircraft_id: 'a1',
    aircraft: mockAircraft[0],
    pilot_id: 'u2',
    pilot: mockUsers[1],
    instructor_id: 'u3',
    instructor: mockUsers[2],
    subject_id: 's1',
    subject: mockSubjects[0],
    launch_method_id: 'lm1',
    launch_method: mockLaunchMethods[0],
    departure_time: `${today}T09:00:00Z`,
    arrival_time: `${today}T09:18:00Z`,
    flight_time: 18,
    departure_place: '大利根飛行場',
    arrival_place: '大利根飛行場',
    landing_count: 1,
    takeoff_count: 1,
    night_landing_count: 0,
    night_takeoff_count: 0,
    pic_type: 'Dual',
    flight_status: 'landed',
    release_altitude: 300,
    max_altitude: 450,
    aircraft_category: 'glider',
    flight_content: '基本操縦訓練',
    dual_instruction_time: 18,
    is_edited: false,
    created_by: 'u1',
    created_at: `${today}T09:00:00Z`,
    updated_at: `${today}T09:18:00Z`,
  },
  {
    id: 'f2',
    aircraft_id: 'a1',
    aircraft: mockAircraft[0],
    pilot_id: 'u2',
    pilot: mockUsers[1],
    instructor_id: 'u3',
    instructor: mockUsers[2],
    subject_id: 's2',
    subject: mockSubjects[1],
    launch_method_id: 'lm1',
    launch_method: mockLaunchMethods[0],
    departure_time: `${today}T10:00:00Z`,
    arrival_time: `${today}T10:22:00Z`,
    flight_time: 22,
    departure_place: '大利根飛行場',
    arrival_place: '大利根飛行場',
    landing_count: 1,
    takeoff_count: 1,
    night_landing_count: 0,
    night_takeoff_count: 0,
    pic_type: 'Dual',
    flight_status: 'landed',
    release_altitude: 320,
    max_altitude: 500,
    aircraft_category: 'glider',
    flight_content: '索道飛行訓練',
    dual_instruction_time: 22,
    is_edited: false,
    created_by: 'u1',
    created_at: `${today}T10:00:00Z`,
    updated_at: `${today}T10:22:00Z`,
  },
  {
    id: 'f3',
    aircraft_id: 'a2',
    aircraft: mockAircraft[1],
    pilot_id: 'u2',
    pilot: mockUsers[1],
    subject_id: 's5',
    subject: mockSubjects[4],
    launch_method_id: 'lm1',
    launch_method: mockLaunchMethods[0],
    departure_time: `${today}T11:00:00Z`,
    flight_time: undefined,
    departure_place: '大利根飛行場',
    arrival_place: '大利根飛行場',
    landing_count: 0,
    takeoff_count: 1,
    night_landing_count: 0,
    night_takeoff_count: 0,
    pic_type: 'Solo',
    flight_status: 'launched',
    aircraft_category: 'glider',
    flight_content: '単独飛行',
    solo_time: undefined,
    is_edited: false,
    created_by: 'u1',
    created_at: `${today}T11:00:00Z`,
    updated_at: `${today}T11:00:00Z`,
  },
  {
    id: 'f4',
    aircraft_id: 'a1',
    aircraft: mockAircraft[0],
    pilot_id: 'u1',
    pilot: mockUsers[0],
    instructor_id: 'u3',
    instructor: mockUsers[2],
    subject_id: 's3',
    subject: mockSubjects[2],
    launch_method_id: 'lm2',
    launch_method: mockLaunchMethods[1],
    departure_time: `2026-05-28T09:30:00Z`,
    arrival_time: `2026-05-28T10:05:00Z`,
    flight_time: 35,
    departure_place: '大利根飛行場',
    arrival_place: '板倉滑空場',
    landing_count: 1,
    takeoff_count: 1,
    night_landing_count: 0,
    night_takeoff_count: 0,
    pic_type: 'Dual',
    flight_status: 'approved',
    release_altitude: 600,
    max_altitude: 1200,
    aircraft_category: 'glider',
    flight_content: '野外飛行訓練',
    dual_instruction_time: 35,
    cross_country_time: 35,
    is_edited: true,
    created_by: 'u1',
    created_at: `2026-05-28T09:30:00Z`,
    updated_at: `2026-05-28T10:30:00Z`,
  },
]

// 承認待ちフライト（教官承認画面用）
mockFlights.push(
  {
    id: 'f5',
    aircraft_id: 'a1',
    aircraft: mockAircraft[0],
    pilot_id: 'u2',
    pilot: mockUsers[1],
    instructor_id: 'u3',
    instructor: mockUsers[2],
    subject_id: 's4',
    subject: mockSubjects[3],
    launch_method_id: 'lm1',
    launch_method: mockLaunchMethods[0],
    departure_time: `${today}T08:10:00Z`,
    arrival_time: `${today}T08:24:00Z`,
    flight_time: 14,
    departure_place: '大利根飛行場',
    arrival_place: '大利根飛行場',
    landing_count: 1,
    takeoff_count: 1,
    night_landing_count: 0,
    night_takeoff_count: 0,
    pic_type: 'Dual',
    flight_status: 'pending_approval',
    release_altitude: 280,
    max_altitude: 380,
    aircraft_category: 'glider',
    flight_content: '場周経路訓練',
    dual_instruction_time: 14,
    is_edited: false,
    created_by: 'u1',
    created_at: `${today}T08:10:00Z`,
    updated_at: `${today}T08:24:00Z`,
  },
  {
    id: 'f6',
    aircraft_id: 'a2',
    aircraft: mockAircraft[1],
    pilot_id: 'u1',
    pilot: mockUsers[0],
    instructor_id: 'u3',
    instructor: mockUsers[2],
    subject_id: 's6',
    subject: mockSubjects[5],
    launch_method_id: 'lm2',
    launch_method: mockLaunchMethods[1],
    departure_time: `2026-06-21T10:40:00Z`,
    arrival_time: `2026-06-21T11:35:00Z`,
    flight_time: 55,
    departure_place: '妻沼滑空場',
    arrival_place: '妻沼滑空場',
    landing_count: 1,
    takeoff_count: 1,
    night_landing_count: 0,
    night_takeoff_count: 0,
    pic_type: 'PIC',
    flight_status: 'pending_approval',
    release_altitude: 550,
    max_altitude: 900,
    aircraft_category: 'glider',
    flight_content: '技量審査',
    pic_time: 55,
    is_edited: true,
    created_by: 'u1',
    created_at: `2026-06-21T10:40:00Z`,
    updated_at: `2026-06-21T12:00:00Z`,
  },
)

export interface Notice {
  id: string
  date: string
  title: string
  body: string
  kind: 'info' | 'warning' | 'maintenance'
}

export const mockNotices: Notice[] = [
  { id: 'n1', date: today, title: '定期メンテナンスのお知らせ', body: `${today} 15:25〜22:00 システムメンテナンスを実施します。`, kind: 'maintenance' },
  { id: 'n2', date: today, title: '今週末の運航予定', body: '土日ともに大利根飛行場で通常運航予定です。', kind: 'info' },
  { id: 'n3', date: '2026-06-28', title: '機体JA02Wの点検完了', body: '耐空検査が完了し、使用可能になりました。', kind: 'info' },
]

export const mockPersonalLogEntries: PersonalLogEntry[] = mockFlights
  .filter(f => f.arrival_time)
  .map((f, i) => ({
    id: `ple-${f.id}`,
    flight_id: f.id,
    flight: f,
    user_id: f.pilot_id,
    aircraft_category: f.aircraft_category,
    date: f.departure_time.split('T')[0],
    aircraft_type: f.aircraft?.aircraft_type ?? '',
    registration_number: f.aircraft?.registration_number ?? '',
    departure_place: f.departure_place,
    arrival_place: f.arrival_place,
    departure_time: f.departure_time,
    arrival_time: f.arrival_time,
    flight_content: f.flight_content,
    landing_count: f.landing_count,
    night_landing_count: f.night_landing_count,
    takeoff_count: f.takeoff_count,
    night_takeoff_count: f.night_takeoff_count,
    total_flight_time: f.flight_time ?? 0,
    pic_time: f.pic_time,
    solo_time: f.solo_time,
    copilot_time: f.copilot_time,
    dual_instruction_time: f.dual_instruction_time,
    cross_country_pic_solo_picus_time: f.cross_country_time,
    other_flight_time: f.other_flight_time,
    instruction_time: f.instruction_time,
    instructor_id: f.instructor_id,
    instructor_name: f.instructor?.name,
    launch_method_id: f.launch_method_id,
    launch_method_name: f.launch_method?.name,
    supplementary_note: f.supplementary_note,
    memo: f.flights_memo,
    logbook_page_no: 1,
    row_no_in_page: i + 1,
    created_at: f.created_at,
  }))

export const mockAircraftLogEntries: AircraftLogEntry[] = mockFlights
  .filter(f => f.arrival_time)
  .map((f, i) => {
    const aircraft = f.aircraft!
    const baseTime = aircraft.aircraft_initial_airframe_time + (i * 20)
    return {
      id: `ale-${f.id}`,
      flight_id: f.id,
      aircraft_id: f.aircraft_id,
      aircraft: f.aircraft,
      aircraft_category: f.aircraft_category,
      aircraft_type: aircraft.aircraft_type,
      registration_number: aircraft.registration_number,
      date: f.departure_time.split('T')[0],
      departure_place: f.departure_place,
      arrival_place: f.arrival_place,
      departure_time: f.departure_time,
      arrival_time: f.arrival_time,
      flight_time: f.flight_time ?? 0,
      pilot_id: f.pilot_id,
      pilot_name: f.pilot?.name ?? '',
      instructor_id: f.instructor_id,
      instructor_name: f.instructor?.name,
      copilot_name: f.copilot_name,
      flight_content: f.flight_content,
      takeoff_count: f.takeoff_count,
      landing_count: f.landing_count,
      night_takeoff_count: f.night_takeoff_count,
      night_landing_count: f.night_landing_count,
      initial_airframe_time: baseTime,
      final_airframe_time: baseTime + (f.flight_time ?? 0),
      initial_flight_count: aircraft.aircraft_initial_flight_count + i,
      final_flight_count: aircraft.aircraft_initial_flight_count + i + 1,
      initial_landing_count: aircraft.aircraft_initial_landing_count + i,
      final_landing_count: aircraft.aircraft_initial_landing_count + i + f.landing_count,
      launch_method_name: f.launch_method?.name,
      release_altitude: f.release_altitude,
      max_altitude: f.max_altitude,
      supplementary_note: f.supplementary_note,
      memo: f.flights_memo,
      created_at: f.created_at,
    }
  })
